### ISSUE TITLE
VRxController - Get ESP32 Status (static and variable)

### ISSUE THREAD

**Issue by ryaniftron** [ryaniftron/RotorHazard#8]
VRxController needs to query the status of the ESP32. 
![image](https://user-images.githubusercontent.com/57248914/81788366-a704de80-94bf-11ea-88aa-713f53c15772.png)

COS:

- VRxC sends requests for status on startup of both variable and static

- When ESP32 joins network, VRxC request for both status

- VRxC subscribes to status and reads the json into rx_data

- VRxC generates events when there is new data

**Comment by Ryanf55** [comment]
This is done and tested.

**Comment by ryaniftron** [comment]
Done and Tested
